// <auto-generated />
using System;
using KryptoCalc.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KryptoCalc.Server.Migrations
{
    [DbContext(typeof(KryptoCalcServerContext))]
    [Migration("20230505154929_AddCoinMarkets2")]
    partial class AddCoinMarkets2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KryptoCalc.Shared.Coin", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Coin");
                });

            modelBuilder.Entity("KryptoCalc.Shared.CoinMarkets", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Ath")
                        .HasColumnType("real");

                    b.Property<float>("AthChangePercentage")
                        .HasColumnType("real");

                    b.Property<DateTime>("AthDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Atl")
                        .HasColumnType("real");

                    b.Property<float>("AtlChangePercentage")
                        .HasColumnType("real");

                    b.Property<DateTime>("AtlDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("CirculatingSupply")
                        .HasColumnType("real");

                    b.Property<float>("CurrentPrice")
                        .HasColumnType("real");

                    b.Property<long>("FullyDilutedValuation")
                        .HasColumnType("bigint");

                    b.Property<float>("High24h")
                        .HasColumnType("real");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<float>("Low24h")
                        .HasColumnType("real");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<float>("MarketCapChange24h")
                        .HasColumnType("real");

                    b.Property<float>("MarketCapChangePercentage24h")
                        .HasColumnType("real");

                    b.Property<int>("MarketCapRank")
                        .HasColumnType("int");

                    b.Property<float>("MaxSupply")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("PriceChange24h")
                        .HasColumnType("real");

                    b.Property<float>("PriceChangePercentage24h")
                        .HasColumnType("real");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("TotalSupply")
                        .HasColumnType("real");

                    b.Property<long>("TotalVolume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CoinMarkets");
                });
#pragma warning restore 612, 618
        }
    }
}
